"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path
from typing import List, Any, Dict

from app.infrastructure.signal.signals import global_ready
from config import app_config_manager, get_environment

# App config instance
_app_config = app_config_manager.get_config()

# Environment
_environment = get_environment()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR: Path = Path(__file__).resolve().parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY: str = 'django-insecure-#d*o%j^-m(#^x&%zq-puu@3bp*yzt-q04-@mpg)nsz*+093v5$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG: bool = _environment in ('local', 'test')

ALLOWED_HOSTS: List[str] = []

LOGGING = {
    'version': 1,
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        }
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler'
        }
    },
    'loggers': {
        'django.db.backends': {
            'level': 'DEBUG',
            'handlers': ['console']
        }
    }
}

# region Django settings

# region Application definition

INSTALLED_APPS: List[str] = [
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Django Rest Framework
    'rest_framework',

    # Swagger UI
    'drf_yasg',

    # Applications
    'app.user',
    'app.todo',
    'app.todo_list',
    'app.workshop'
]

MIDDLEWARE: List[str] = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'app.infrastructure.middleware.thread_local_middleware.ThreadLocalMiddleware'
]

ROOT_URLCONF: str = 'app.urls'

TEMPLATES: List[Dict[str, Any]] = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION: str = 'app.wsgi.application'

AUTH_USER_MODEL = 'user.User'
# endregion

# region Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
DATABASES: Dict[str, Any] = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': _app_config.MYSQL_HOST,
        'PORT': _app_config.MYSQL_PORT,
        'USER': _app_config.MYSQL_USERNAME,
        'PASSWORD': _app_config.MYSQL_PASSWORD,
        'NAME': _app_config.MYSQL_DB_NAME,
        'OPTIONS': {
            'charset': _app_config.MYSQL_DB_CHARSET
        }
    }
}
# endregion


# region Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE: str = 'en-us'

TIME_ZONE: str = 'UTC'

USE_I18N: bool = True

USE_TZ: bool = True
# endregion


# region Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
STATIC_ROOT: str = os.path.join(BASE_DIR, "static_files")
STATIC_URL: str = 'static/'
# endregion

# region Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field
# DEFAULT_AUTO_FIELD must subclass AutoField
DEFAULT_AUTO_FIELD: str = 'django.db.models.AutoField'
# endregion

# endregion


# region Django Rest Framework settings
REST_FRAMEWORK: Dict[str, Any] = {
    'UNAUTHENTICATED_USER': 'app.user.models.UnauthenticatedUser',

    # https://www.django-rest-framework.org/api-guide/settings/#default_authentication_classes
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'app.security.auth0_authentication.Auth0Authentication'
    ],

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ],

    # https://www.django-rest-framework.org/api-guide/renderers/#renderers
    'DEFAULT_RENDERER_CLASSES': [
        'app.infrastructure.renderer.api_renderer.APIRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ]
}
# endregion


# region Swagger settings
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False
}
# endregion


# Send global ready signal
global_ready.send(_app_config)
