# Generated by Django 4.1.6 on 2023-02-14 11:16

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def insert_user_statuses(apps: Apps, schema_monitor: BaseDatabaseSchemaEditor) -> None:
    UserStatus = apps.get_model('user', 'UserStatus')

    UserStatus.objects.create(id=1, name='Enabled')
    UserStatus.objects.create(id=2, name='Disabled')


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_user_statuses)
    ]
