# Generated by Django 4.1.7 on 2023-02-28 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_guest_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='references_to', to='workshop.guest'),
        ),
    ]
