# Generated by Django 4.1.6 on 2023-02-14 11:16

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def insert_todo_statuses(apps: Apps, schema_monitor: BaseDatabaseSchemaEditor) -> None:
    TodoStatus = apps.get_model('todo', 'TodoStatus')

    TodoStatus.objects.create(id=1, name='Open')
    TodoStatus.objects.create(id=2, name='Closed')
    TodoStatus.objects.create(id=3, name='Expired')
    TodoStatus.objects.create(id=4, name='Deleted')


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_todo_statuses)
    ]


