# Generated by Django 4.1.6 on 2023-02-14 12:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoListStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todo_list.todoliststatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='todo_lists', to='user.user')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
    ]
