# Generated by Django 4.1.6 on 2023-02-14 11:16

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def insert_todo_list_statuses(apps: Apps, schema_monitor: BaseDatabaseSchemaEditor) -> None:
    TodoListStatus = apps.get_model('todo_list', 'TodoListStatus')

    TodoListStatus.objects.create(id=1, name='Open')
    TodoListStatus.objects.create(id=2, name='Closed')
    TodoListStatus.objects.create(id=3, name='Deleted')


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_todo_list_statuses)
    ]


